#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

FLATNOTES_AUTH_TYPE =  data.get("FLATNOTES_AUTH_TYPE", "password")
FLATNOTES_USERNAME = data.get("FLATNOTES_USERNAME", "admin")
FLATNOTES_PASSWORD = data.get("FLATNOTES_PASSWORD", "admin")
#This is specific to you module, so you need to change it accordingly.
flatnotes = {
    "FLATNOTES_AUTH_TYPE": FLATNOTES_AUTH_TYPE,
    "FLATNOTES_USERNAME": FLATNOTES_USERNAME,
    "FLATNOTES_PASSWORD": FLATNOTES_PASSWORD
}
agent.write_envfile("flatnotes.env", flatnotes)
#agent.dump_env()
