#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
FLATNOTES_SECRET_KEY = secrets.token_safeurl(32)
flat_notes = {
    "FLATNOTES_SECRET_KEY": FLATNOTES_SECRET_KEY
}
agent.write_envfile("secrets.env", flat_notes)


# just before starting systemd unit
#agent.dump_env()
